POST    http://localhost:3000/upload/file HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file.txt"
Content-Type: text/plain

< static/file.txt
------WebKitFormBoundary7MA4YWxkTrZu0gW--